### ISSUE TITLE
Map floating numbers to custom string field

### ISSUE THREAD

**Issue by mergene** [rabobank-cdc/dtctl#1]
cfp1 and cfp2 is not indexed by default on ArcSight. Can you map those values to cs1 and cs2? 

'Packet Loss': {
            'packet_loss': 'cfp1Label', -->change to cs1Label
            'worker_drop_rate': 'cfp2Label' --> change to cs2Label
.
.
.
elif isinstance(value, float):
                float_counter += 1
                line += 'cf{counter}Label={k} cf{counter}={v} '.format(counter=float_counter, v=value, k=key) --> change “cf” to “cs”

**Comment by daanwa** [comment]
@mergene I changed the labels for the Packet Loss mapping.

However, the cfX in the ```convert_to_custom_cef_fields``` functions will remain as is because they are dynamically determined based on object type. Do note that this function is currently not in use.
